# Generated by Django 5.2.9 on 2026-02-02 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarbonLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_amount', models.FloatField(help_text='Amount of Carbon saved (kg/g)')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carbon_logs', to='lims.zone')),
            ],
        ),
    ]
